### ISSUE TITLE
点击设置闪退

### ISSUE THREAD

**Issue by pingping1314520** [Mikotwa/FuckLocation#23]
API 版本
93

注入接口
Zygisk

框架版本
1.7.2 (6379)

管理器版本
1.7.2 (6379)

系统版本
12 (API 31)

设备
Xiaomi Mi 10 

系统架构
arm64-v8a

日志：
----part 2 start----
[ 2022-02-18T16:01:49.914        0:   952:  1357 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-02-18T16:01:49.913.log
[ 2022-02-18T16:01:55.360        0:   952:  1193 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-02-18T16:01:55.365        0:   952:  1357 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-02-18T16:01:55.365.log
[ 2022-02-18T16:02:01.367    10230: 23246: 23246 I/LSPosed         ] Loading modules for fuck.location/10230
[ 2022-02-18T16:02:01.368    10230: 23246: 23246 I/LSPosed-Bridge  ] Loading module fuck.location from /data/app/~~Ha8Q5quwCSaC_9Vnhg96AQ==/fuck.location-q791WxtTBGJ0H5QIs5Exfg==/base.apk
[ 2022-02-18T16:02:01.410    10230: 23246: 23246 I/LSPosed-Bridge  ]   Loading class fuck.location.xposed.HookEntry
[ 2022-02-18T16:02:01.414    10230: 23246: 23246 I/LSPosed-Bridge  ] FL: in initZygote!
[ 2022-02-18T16:02:01.465    10230: 23246: 23246 I/LSPosed-Bridge  ] FL: Try to hook the module
[ 2022-02-18T16:02:01.518    10230: 23246: 23246 I/LSPosed-Bridge  ] FL: Unlock the module
[ 2022-02-18T16:02:02.296     1000: 23377: 23377 I/LSPosed         ] Loading modules for com.miui.securitycenter/1000
[ 2022-02-18T16:02:02.297     1000: 23377: 23377 I/LSPosed-Bridge  ] Loading module cn.coderstory.miui.water from /data/app/~~VXqU97MYuQi0W59r7yIC-g==/cn.coderstory.miui.water-nJjcS081l2XZqftf829KWg==/base.apk
[ 2022-02-18T16:02:02.300     1000: 23377: 23377 I/LSPosed-Bridge  ]   Loading class cn.coderstory.miui.water.MainHook
[ 2022-02-18T16:02:53.008    10230: 23246: 23246 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
	at android.view.View.performClick(View.java:7750)
	at android.view.View.performClickInternal(View.java:7727)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29144)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8211)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
	... 15 more
[ 2022-02-18T16:02:53.009    10230: 23246: 23246 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: fuck.location, PID: 23246
java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
	at android.view.View.performClick(View.java:7750)
	at android.view.View.performClickInternal(View.java:7727)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29144)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8211)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
	... 15 more

**Comment by Mikotwa** [comment]
> Crash unexpectedly: java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;

该问题无法在我的 MIUI 上复现，且未见类似问题的反馈。
需要稳定复现的方法
