### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by GeekTR** [Mikotwa/FuckLocation#25]
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/13369103/154847106-8a141934-d7f0-44b8-bcd5-20e357f6b764.png">
第一次安装过FuckLocation时，点击位置白名单和设置时会闪退。看了下崩溃日志，是这两行导致的，应该是在非hook的环境使用Xposed的Api导致的。还有就是hook刚激活没有生效（没有重启）时，点击设置白名单，然后随便点击一个app，也会闪退

**Comment by Mikotwa** [comment]
> 第一次安装过FuckLocation时，点击位置白名单和设置时会闪退。

> hook刚激活没有生效（没有重启）时，点击设置白名单，然后随便点击一个app，也会闪退

正常情况下，似乎不存在这种情况？毕竟该模块在未激活 Hook 之前不开放白名单功能。能说明一下是什么流程会出现这种情况吗？

**Comment by GeekTR** [comment]
就是第一次安装，然后激活，但是没有重启手机，然后进入模块设置页面进行操作。很好复现的，你先卸载掉，然后重启手机，然后重新装一个，然后激活模块，不要重启，直接进设置。

**Comment by Mikotwa** [comment]
我估计猜到是什么情况了。你说的应该是：
- 在 LSPosed 里激活模块。此时模块可以立即 Hook 自己，使得原本设计为“模块未激活”的内容被顺利激活
- 但此时系统还未重启，针对系统的 Hook 并未实质生效。此时使用白名单功能将会导致程序崩溃

这看起来是一个逻辑 Bug。会在后期加入额外的判断逻辑以避免

**Comment by Robin-zero** [comment]
同样的现象，但是我的重启了依旧闪退，附上日志截图![Screenshot_2022-02-24-02-08-44-265_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/22169252/155380959-ef8af88c-8b7a-47ae-a93b-63bad472dd25.jpg)

**Comment by Mikotwa** [comment]
> 同样的现象，但是我的重启了依旧闪退，附上日志截图![Screenshot_2022-02-24-02-08-44-265_com.miui.bugreport.jpg](https://user-images.githubusercontent.com/22169252/155380959-ef8af88c-8b7a-47ae-a93b-63bad472dd25.jpg)

发日志

**Comment by rojunghwa** [comment]
同样也是闪退  日志如下

<details>

```
[ 2022-02-27T22:27:46.842    10247: 16314: 16314 I/LSPosed-Bridge  ] Loading module fuck.location from /data/app/fuck.location-dOjerrEimo9-LBEO21n1hw==/base.apk
[ 2022-02-27T22:27:47.186    10247: 16314: 16314 I/LSPosed-Bridge  ]   Loading class fuck.location.xposed.HookEntry
[ 2022-02-27T22:27:47.197    10247: 16314: 16314 I/LSPosed-Bridge  ] FL: in initZygote!
[ 2022-02-27T22:27:47.299    10247: 16314: 16314 I/LSPosed-Bridge  ] FL: Try to hook the module
[ 2022-02-27T22:27:47.410    10247: 16314: 16314 I/LSPosed-Bridge  ] FL: Unlock the module
[ 2022-02-27T22:27:49.472    10247: 16314: 16314 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3500(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
```
</details>


<details>

```
----part 3 start----
[ 2022-02-27T22:27:40.420        0:   641:  1359 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-02-27T22:27:40.419.log
[ 2022-02-27T22:27:46.840    10247: 16314: 16314 I/LSPosed         ] Loading modules for fuck.location/10247
[ 2022-02-27T22:27:46.842    10247: 16314: 16314 I/LSPosed-Bridge  ] Loading module fuck.location from /data/app/fuck.location-dOjerrEimo9-LBEO21n1hw==/base.apk
[ 2022-02-27T22:27:47.186    10247: 16314: 16314 I/LSPosed-Bridge  ]   Loading class fuck.location.xposed.HookEntry
[ 2022-02-27T22:27:47.197    10247: 16314: 16314 I/LSPosed-Bridge  ] FL: in initZygote!
[ 2022-02-27T22:27:47.299    10247: 16314: 16314 I/LSPosed-Bridge  ] FL: Try to hook the module
[ 2022-02-27T22:27:47.410    10247: 16314: 16314 I/LSPosed-Bridge  ] FL: Unlock the module
[ 2022-02-27T22:27:49.472    10247: 16314: 16314 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3500(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
	... 14 more
[ 2022-02-27T22:27:49.472    10247: 16314: 16314 E/AndroidRuntime  ] FATAL EXCEPTION: main
Process: fuck.location, PID: 16314
java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3500(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:242)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
	... 14 more

```
</details>

**Comment by steve02081504** [comment]
闪退+1，不知是不是同一个问题
```
[ 2022-06-23T09:01:11.671     1000:  1980:  2248 I/LSPosed-Bridge  ] FL: In getConnectionInfo with caller: com.android.systemui
[ 2022-06-23T09:01:11.671     1000:  1980:  2248 E/LSPosed-Bridge  ] java.lang.NoSuchMethodException: Cannot find matching method
	at org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Unknown Source:112)
	at fuck.location.xposed.helpers.ConfigGateway.universalAPICaller(ConfigGateway.kt:249)
	at fuck.location.xposed.helpers.ConfigGateway.inWhitelist(ConfigGateway.kt:260)
	at fuck.location.xposed.location.WLANHooker$hookWifiManager$2$1$4$1.invoke(WLANHooker.kt:62)
	at fuck.location.xposed.location.WLANHooker$hookWifiManager$2$1$4$1.invoke(WLANHooker.kt:58)
	at com.github.kyuubiran.ezxhelper.utils.XposedHookUtilFactory.afterHookedMethod(HookUtils.kt:361)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getConnectionInfo(Unknown Source:14)
	at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:926)
	at com.android.server.wifi.WifiServiceImplEx.onTransact(WifiServiceImplEx.java:580)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
[ 2022-06-23T09:01:14.253    10379:  8839:  8839 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: java.lang.NoSuchMethodException: Cannot find matching method
	at org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Unknown Source:112)
	at fuck.location.xposed.helpers.ConfigGateway.universalAPICaller(ConfigGateway.kt:249)
	at fuck.location.xposed.helpers.ConfigGateway.writeFakeLocation(ConfigGateway.kt:325)
	at fuck.location.app.ui.activities.MainActivity$setFakeLocation$1$1.invoke(MainActivity.kt:113)
	at fuck.location.app.ui.activities.MainActivity$setFakeLocation$1$1.invoke(MainActivity.kt:89)
	at com.afollestad.materialdialogs.callbacks.DialogCallbackExtKt.invokeAll(DialogCallbackExt.kt:68)
	at com.afollestad.materialdialogs.MaterialDialog.onActionButtonClicked$core(MaterialDialog.kt:406)
	at com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout$onFinishInflate$1.onClick(DialogActionButtonLayout.kt:84)
	at android.view.View.performClick(View.java:7452)
	at android.view.View.performClickInternal(View.java:7429)
	at android.view.View.access$4100(View.java:839)
	at android.view.View$PerformClick.run(View.java:28764)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8001)
	... 3 more
```
