### ISSUE TITLE
安卓11设置直接崩溃，能否支持基站模拟？

### ISSUE THREAD

**Issue by leezn** [Mikotwa/FuckLocation#27]
java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readPackageList(ConfigGateway.kt:269)
	at fuck.location.app.ui.activities.ModuleActivity$AppListModule.<init>(ModuleActivity.kt:150)
	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:48)
	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:47)
	at com.idanatz.oneadapter.OneAdapter.<init>(OneAdapter.kt:29)
	at fuck.location.app.ui.activities.ModuleActivity.onCreate(ModuleActivity.kt:47)
	at android.app.Activity.performCreate(Activity.java:8235)
	at android.app.Activity.performCreate(Activity.java:8206)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3548)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3735)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2168)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
	... 21 more

**Comment by Mikotwa** [comment]
请重启后再到 LSPosed 里导出完整日志

**Comment by leezn** [comment]
> 请重启后再到 LSPosed 里导出完整日志

有点奇怪了，我下载了Actions生成的测试版的1.2.10，点设置不崩溃了，但是设置的不生效，位置都不行。卸载重新安装1.2.9版本的，点设置居然也不崩溃了，同时设置的坐标信息还在，并没有消失，但是仍旧不生效。小米9  MIUI 12.5  21.11.24  Android11

**Comment by Mikotwa** [comment]
> > 请重启后再到 LSPosed 里导出完整日志
> 
> 有点奇怪了，我下载了Actions生成的测试版的1.2.10，点设置不崩溃了，但是设置的不生效，位置都不行。卸载重新安装1.2.9版本的，点设置居然也不崩溃了，同时设置的坐标信息还在，并没有消失，但是仍旧不生效。小米9 MIUI 12.5 21.11.24 Android11

我没法通过你的描述精确定位问题在哪里，请发日志

**Comment by GeekTR** [comment]
#25 同一个问题

**Comment by leezn** [comment]
抓取的2份log，麻烦大佬看看能不能分析[LSPosed_2022-02-24T22_21_51.177.zip](https://github.com/Mikotwa/FuckLocation/files/8149757/LSPosed_2022-02-24T22_21_51.177.zip)
[LSPosed_2022-02-25T10_15_52.223.zip](https://github.com/Mikotwa/FuckLocation/files/8149759/LSPosed_2022-02-25T10_15_52.223.zip)

**Comment by Mikotwa** [comment]
> 抓取的2份log，麻烦大佬看看能不能分析[LSPosed_2022-02-24T22_21_51.177.zip](https://github.com/Mikotwa/FuckLocation/files/8149757/LSPosed_2022-02-24T22_21_51.177.zip) [LSPosed_2022-02-25T10_15_52.223.zip](https://github.com/Mikotwa/FuckLocation/files/8149759/LSPosed_2022-02-25T10_15_52.223.zip)

> Crash unexpectedly: java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;

看起来这是问题所在。但我的机器上无法复现这一问题。你可以试试看暂时只开启 Fuck Location，然后重启后查看该问题是否依然存在

**Comment by leezn** [comment]
目前使用的CI的生成的版本，可以正常使用了，希望后期可以地图选点的功能，以及可以在所设置位置自动偏移2-5m，有些软件会上报经纬度，但是每次都是同一个经纬度，会异常

**Comment by Mikotwa** [comment]
> 希望后期可以地图选点的功能

有计划，但受制于非技术原因，无法使用中国大陆的定位 SDK，敬请谅解。

> 可以在所设置位置自动偏移2-5m，有些软件会上报经纬度，但是每次都是同一个经纬度，会异常

很棒的提议！会考虑在未来的版本中加入
