### ISSUE TITLE
点击白名单或程序设置将导致闪退

### ISSUE THREAD

**Issue by XiongUp** [Mikotwa/FuckLocation#34]
### Steps to reproduce / 复现步骤

安装并激活模块后重启，进入程序点击白名单或者设置将导致闪退

### Expected behaviour / 预期行为

正常情况下应可以设置白名单、设置位置信息

### Actual behaviour / 实际行为

实际发生闪退无法设置

### Android version / Android 版本

12

### OEM Information / OEM 信息

MIUI13

### Logs / 日志

[LSPosed_2022-04-09T16_33_03.861.zip](https://github.com/Mikotwa/FuckLocation/files/8456581/LSPosed_2022-04-09T16_33_03.861.zip)

```
04-09 16:32:45.988 18384 18384 D AndroidRuntime: Shutting down VM
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: Crash unexpectedly: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: Caused by: java.lang.reflect.InvocationTargetException
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	... 1 more
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1152)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:384)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:206)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:38)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:290)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.view.View.performClick(View.java:7750)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.view.View.performClickInternal(View.java:7727)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.view.View.access$3700(View.java:861)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.view.View$PerformClick.run(View.java:29143)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:938)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:210)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:299)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:8265)
04-09 16:32:45.989 18384 18384 I LSPosed-Bridge: 	... 3 more
04-09 16:32:45.989 18384 18384 E AndroidRuntime: FATAL EXCEPTION: main
04-09 16:32:45.989 18384 18384 E AndroidRuntime: Process: fuck.location, PID: 18384
04-09 16:32:45.989 18384 18384 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	... 1 more
04-09 16:32:45.989 18384 18384 E AndroidRuntime: Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1152)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:384)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:206)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:38)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:290)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.view.View.performClick(View.java:7750)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7727)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.view.View.access$3700(View.java:861)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:29143)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8265)
04-09 16:32:45.989 18384 18384 E AndroidRuntime: 	... 3 more
```
```
04-09 16:32:55.003 18602 18602 E AndroidRuntime: FATAL EXCEPTION: main
04-09 16:32:55.003 18602 18602 E AndroidRuntime: Process: fuck.location, PID: 18602
04-09 16:32:55.003 18602 18602 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{fuck.location/fuck.location.app.ui.activities.ModuleActivity}: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3748)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8265)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1152)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:384)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:206)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:38)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at fuck.location.xposed.helpers.ConfigGateway.readPackageList(ConfigGateway.kt:273)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at fuck.location.app.ui.activities.ModuleActivity$AppListModule.<init>(ModuleActivity.kt:150)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:48)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:47)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at com.idanatz.oneadapter.OneAdapter.<init>(OneAdapter.kt:29)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at fuck.location.app.ui.activities.ModuleActivity.onCreate(ModuleActivity.kt:47)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8241)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8207)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3721)
04-09 16:32:55.003 18602 18602 E AndroidRuntime: 	... 12 more
```

### Final checklist / 发布前检查清单

- [X] I have searched the Issues and Discussions to make sure it had not reported / 我已经在 Issue 和 Discussion 区搜索过，该问题未被报告过
- [X] I have read the Q&A and I am sure my issue is not related to them / 我已经阅读过常见问题解答，且确定我的问题与它们无关
- [ ] I am using the latest debug CI version of Fuck Location and enabled verbose log / 我正在使用最新的 CI 调试版本，并且启用了详细日志

**Comment by Mikotwa** [comment]
看起来像你的配置文件坏了。删一下 /data/system/fuck_location_xxx（随机字符串）里面的 json 文件

**Comment by XiongUp** [comment]
删除后，上述问题得到了解决。但是类似百度地图应用打开后显示定位失败

**Comment by Mikotwa** [comment]
> 删除后，上述问题得到了解决。但是类似百度地图应用打开后显示定位失败

请尝试完善基站信息

**Comment by XiongUp** [comment]
已完善了信息，但问题并未得到解决，即便安装CI版本也没有起作用，是否需要提供日志文件？

**Comment by Mikotwa** [comment]
> 即便安装CI版本也没有起作用，是否需要提供日志文件？

安装次新一版的 CI，然后发日志文件

**Comment by getr00t** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readPackageList(ConfigGateway.kt:269)
	at fuck.location.app.ui.activities.ModuleActivity$AppListModule.<init>(ModuleActivity.kt:150)
	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:48)
	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:47)
	at com.idanatz.oneadapter.OneAdapter.<init>(OneAdapter.kt:29)
	at fuck.location.app.ui.activities.ModuleActivity.onCreate(ModuleActivity.kt:47)
	at android.app.Activity.performCreate(Activity.java:7232)
	at android.app.Activity.performCreate(Activity.java:7221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XposedBridge" on path: DexPathList[[zip file "/data/app/fuck.location-9VxQtParFpGN6NnRafA_5Q==/base.apk"],nativeLibraryDirectories=[/data/app/fuck.location-9VxQtParFpGN6NnRafA_5Q==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 21 more
我出现这个问题

**Comment by getr00t** [comment]
> > 即便安装CI版本也没有起作用，是否需要提供日志文件？
> 
> 安装次新一版的 CI，然后发日志文件

java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readPackageList(ConfigGateway.kt:269)
	at fuck.location.app.ui.activities.ModuleActivity$AppListModule.<init>(ModuleActivity.kt:150)
	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:48)
	at fuck.location.app.ui.activities.ModuleActivity$onCreate$1.invoke(ModuleActivity.kt:47)
	at com.idanatz.oneadapter.OneAdapter.<init>(OneAdapter.kt:29)
	at fuck.location.app.ui.activities.ModuleActivity.onCreate(ModuleActivity.kt:47)
	at android.app.Activity.performCreate(Activity.java:7232)
	at android.app.Activity.performCreate(Activity.java:7221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XposedBridge" on path: DexPathList[[zip file "/data/app/fuck.location-9VxQtParFpGN6NnRafA_5Q==/base.apk"],nativeLibraryDirectories=[/data/app/fuck.location-9VxQtParFpGN6NnRafA_5Q==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 21 more
我出现这个问题

**Comment by WeihuaGu** [comment]
跟 getr00t 情况一样，都是
java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge
系统是安卓13

**Comment by getr00t** [comment]
> 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13

你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置

**Comment by WeihuaGu** [comment]
> > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> 
> 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置

你咋不闪退的

**Comment by getr00t** [comment]
> > > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> > 
> > 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置
> 
> 你咋不闪退的

我啥也没做，之前研究了下不会设置使用，最近又打开发现没有闪退了，我刷机过，应该给我刷机没关系吧，你也可以试试

**Comment by ClockworkChen** [comment]
> 闪

兄弟解决了吗，我也遇到同样问题，miui12.5.6 android11

**Comment by clockworkchen** [comment]
> > > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> > 
> > 
> > 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置
> 
> 你咋不闪退的

兄弟解决了吗，我也遇到同样问题，miui12.5.6 android11

**Comment by getr00t** [comment]
> > > > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> > > 
> > > 
> > > 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置
> > 
> > 你咋不闪退的
> 
> 兄弟解决了吗，我也遇到同样问题，miui12.5.6 android11

重启一次手机，就可以了，你可以试试

**Comment by ClockworkChen** [comment]
> > > > > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> > > > 
> > > > 
> > > > 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置
> > > 
> > > 
> > > 你咋不闪退的
> > 
> > 
> > 兄弟解决了吗，我也遇到同样问题，miui12.5.6 android11
> 
> 重启一次手机，就可以了，你可以试试

不行额。

**Comment by clockworkchen** [comment]
> > > > > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> > > > 
> > > > 
> > > > 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置
> > > 
> > > 
> > > 你咋不闪退的
> > 
> > 
> > 兄弟解决了吗，我也遇到同样问题，miui12.5.6 android11
> 
> 重启一次手机，就可以了，你可以试试

之前重启了不行，这次居然行了，之前重启了几次还显示模块未激活。

**Comment by clockworkchen** [comment]
会不会是勾选hook应用的时候要同时勾选系统框架，然后电话那里也不勾选。

**Comment by getr00t** [comment]
> > > > > > 跟 getr00t 情况一样，都是 java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge 系统是安卓13
> > > > > 
> > > > > 
> > > > > 你的可以使用了吗，我的不闪退了，但是不会使用，不懂怎么使用这个坐标设置
> > > > 
> > > > 
> > > > 你咋不闪退的
> > > 
> > > 
> > > 兄弟解决了吗，我也遇到同样问题，miui12.5.6 android11
> > 
> > 
> > 重启一次手机，就可以了，你可以试试
> 
> 之前重启了不行，这次居然行了，之前重启了几次还显示模块未激活。

那是你没勾选作用域吧就提示未激活，我设置了经纬度就是无效，你现在可以正常虚拟地址吗，我的设置了就是没法成功虚拟成功

**Comment by getr00t** [comment]
> 会不会是勾选hook应用的时候要同时勾选系统框架，然后电话那里也不勾选。

我是勾选了系统框架的，电话我是取消了的，不知道电话是不是必须要勾选，反正我设置了经纬度后虚拟地址在微信里面使用是没生效的，你的可以正常使用吗

**Comment by clockworkchen** [comment]
是的，无法虚拟成功，始终显示服务了0次，edposed和lsposed都试过，都不行。
