### ISSUE TITLE
设置时闪退

### ISSUE THREAD

**Issue by yuehun** [Mikotwa/FuckLocation#45]
### Steps to reproduce / 复现步骤

设置定位坐标和设置位置白名单闪退

### Expected behaviour / 预期行为

设置定位坐标和设置位置白名单闪退

### Actual behaviour / 实际行为

设置定位坐标和设置位置白名单闪退

### Android version / Android 版本

12

### Logs / 日志

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
 ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Unknown Source:102)
 at fuck.location.xposed.helpers.ConfigGateway.universalAPICaller(ConfigGateway.kt:249)
 at fuck.location.xposed.helpers.ConfigGateway.writeFakeLocation(ConfigGateway.kt:325)
 at fuck.location.app.ui.activities.MainActivity$setFakeLocation$1$1.invoke(MainActivity.kt:113)
 at fuck.location.app.ui.activities.MainActivity$setFakeLocation$1$1.invoke(MainActivity.kt:89)
 at com.afollestad.materialdialogs.callbacks.DialogCallbackExtKt.invokeAll(DialogCallbackExt.kt:68)
 at com.afollestad.materialdialogs.MaterialDialog.onActionButtonClicked$core(MaterialDialog.kt:406)
 at com.afollestad.materialdialogs.internal.button.DialogActionButtonLayout$onFinishInflate$1.onClick(DialogActionButtonLayout.kt:84)
 at android.view.View.performClick(View.java:7750)
 at android.view.View.performClickInternal(View.java:7727)
 at android.view.View.access$3700(View.java:861)
 at android.view.View$PerformClick.run(View.java:29143)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:210)
 at android.os.Looper.loop(Looper.java:299)
 at android.app.ActivityThread.main(ActivityThread.java:8283)
 ... 3 more
Caused by: java.lang.SecurityException: Only shell can call it
 at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
 at android.os.Parcel.createException(Parcel.java:2409)
 at android.os.Parcel.readException(Parcel.java:2392)
 at android.os.Parcel.readException(Parcel.java:2334)
 at android.app.IActivityManager$Stub$Proxy.setProcessMemoryTrimLevel(IActivityManager.java:9547)
 at android.app.ActivityManager.setProcessMemoryTrimLevel(ActivityManager.java:3370)
 ... 21 more
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.am.ActivityManagerService.setProcessMemoryTrimLevel(ActivityManagerService.java:2899)
 at java.lang.reflect.Method.invoke(Native Method)
 at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
 at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
 at LSPHooker_.setProcessMemoryTrimLevel(Unknown Source:25)

### Final checklist / 发布前检查清单

- [ ] I have searched the Issues and Discussions to make sure it had not reported / 我已经在 Issue 和 Discussion 区搜索过，该问题未被报告过
- [ ] I have read the Q&A and I am sure my issue is not related to them / 我已经阅读过常见问题解答，且确定我的问题与它们无关
- [ ] I am using the latest debug CI version of Fuck Location and enabled verbose log / 我正在使用最新的 CI 调试版本，并且启用了详细日志

**Comment by Springrx** [comment]
请问这个问题你解决了吗？我分别尝试安装了fuck location 1.2.13和1.2.11版本，都遇到了相似的闪退问题，我的机型是红米K20Pro，系统版本Android11。
