### ISSUE TITLE
小米6模拟定位不生效

### ISSUE THREAD

**Issue by BandageWorm** [Mikotwa/FuckLocation#46]
[LSPosed_2022-07-06T17_27_57.453.zip](https://github.com/Mikotwa/FuckLocation/files/9053626/LSPosed_2022-07-06T17_27_57.453.zip)

`07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/telephony/CellIdentityNr;
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at fuck.location.xposed.cellar.PhoneInterfaceManagerHooker$hookCellLocation$6$1.invoke(PhoneInterfaceManagerHooker.kt:74)
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at fuck.location.xposed.cellar.PhoneInterfaceManagerHooker$hookCellLocation$6$1.invoke(PhoneInterfaceManagerHooker.kt:62)
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at com.github.kyuubiran.ezxhelper.utils.XposedHookUtilFactory.afterHookedMethod(HookUtils.kt:361)
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at LSPHooker_.getCellLocation(Unknown Source:11)
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at com.android.internal.telephony.ITelephony$Stub.onTransact(ITelephony.java:465)
07-06 17:17:18.589  2769  2938 E LSPosed-Bridge: 	at android.os.Binder.execTransact(Binder.java:726)`
不知道跟这个是否有关

**Comment by BandageWorm** [comment]
似乎安卓9的miui11 12均有此问题

**Comment by FanDuiWuXiaoJiaBan** [comment]
同mi6同样错误
