### ISSUE TITLE
[Report Issue / 反馈问题] Fuck不生效

### ISSUE THREAD

**Issue by w311ang** [Mikotwa/FuckLocation#51]
### Steps to reproduce / 复现步骤

1. 安装激活模块
2. 重启
3. 作用域选择需要作用的应用
4. 强行停止该应用并启动

### Expected behaviour / 预期行为

正常Fuck定位

### Actual behaviour / 实际行为

仍然是真实定位

### Android version / Android 版本

12

### OEM Information / OEM 信息

ColorOS V12.1

### Logs / 日志

```
kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class java.lang.String
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:328)
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:44)
	at kotlin.reflect.full.KClassifiers.createType(KClassifiers.kt:48)
	at kotlin.reflect.jvm.internal.ReflectionFactoryImpl.typeOf(ReflectionFactoryImpl.java:124)
	at kotlin.jvm.internal.Reflection.typeOf(Reflection.java:127)
	at fuck.location.xposed.helpers.ConfigGateway.inWhitelistOrNot(ConfigGateway.kt:380)
	at fuck.location.xposed.helpers.ConfigGateway.access$inWhitelistOrNot(ConfigGateway.kt:31)
	at fuck.location.xposed.helpers.ConfigGateway$hookWillChangeBeEnabled$2$1.invoke(ConfigGateway.kt:79)
	at fuck.location.xposed.helpers.ConfigGateway$hookWillChangeBeEnabled$2$1.invoke(ConfigGateway.kt:75)
	at com.github.kyuubiran.ezxhelper.utils.XposedHookUtilFactory.beforeHookedMethod(HookUtils.kt:357)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.setProcessMemoryTrimLevel(Unknown Source:25)
	at android.app.ActivityManager.setProcessMemoryTrimLevel(ActivityManager.java:3350)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.hiddenapibypass.HiddenApiBypass.invoke(Unknown Source:102)
	at fuck.location.xposed.helpers.ConfigGateway.universalAPICaller(ConfigGateway.kt:249)
	at fuck.location.xposed.helpers.ConfigGateway.inWhitelist(ConfigGateway.kt:260)
	at fuck.location.xposed.cellar.TelephonyRegistryHooker$hookListen$2.invoke(TelephonyRegistryHooker.kt:37)
	at fuck.location.xposed.cellar.TelephonyRegistryHooker$hookListen$2.invoke(TelephonyRegistryHooker.kt:25)
	at com.github.kyuubiran.ezxhelper.utils.HookUtilsKt$hookAfter$1.afterHookedMethod(HookUtils.kt:118)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.validateEventAndUserLocked(Unknown Source:18)
	at com.android.server.TelephonyRegistry.notifyCellInfoForSubscriber(TelephonyRegistry.java:1798)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.notifyCellInfoForSubscriber(Unknown Source:18)
	at com.android.internal.telephony.ITelephonyRegistry$Stub.onTransact(ITelephonyRegistry.java:612)
	at android.os.Binder.execTransactInternal(Binder.java:1226)
	at android.os.Binder.execTransact(Binder.java:1163)
```

### Final checklist / 发布前检查清单

- [X] I have searched the Issues and Discussions to make sure it had not reported / 我已经在 Issue 和 Discussion 区搜索过，该问题未被报告过
- [X] I have read the Q&A and I am sure my issue is not related to them / 我已经阅读过常见问题解答，且确定我的问题与它们无关
- [X] I am using the latest debug CI version of Fuck Location and enabled verbose log / 我正在使用最新的 CI 调试版本，并且启用了详细日志

**Comment by w311ang** [comment]
说下我的错误吧，首先不要在作用域选择其他应用，而是在模块设置内白名单选择要fuck的应用，亲测高德地图需要等真实位置出来一会再等等就会出现fuck的位置，出现上述错误可以尝试再次重启手机也许就好了，再不行可以尝试关闭隐藏应用列表这个模块和其magisk增强模块
