### ISSUE TITLE
不应该在android消息loop中直接调用xposed api

### ISSUE THREAD

**Issue by q178666380** [Mikotwa/FuckLocation#55]
### Steps to reproduce / 复现步骤

android高版本,点击任意设置键即可崩溃

### Expected behaviour / 预期行为

进去设置

### Actual behaviour / 实际行为

崩溃

### Android version / Android 版本

11

### Logs / 日志

java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
	at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
	at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
	at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
	at android.view.View.performClick(Unknown Source:17)
	at android.view.View.performClickInternal(Unknown Source:3)
	at android.view.View.access$3600(Unknown Source:0)
	at android.view.View$PerformClick.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
	... 14 more

### Final checklist / 发布前检查清单

- [ ] I have searched the Issues and Discussions to make sure it had not reported / 我已经在 Issue 和 Discussion 区搜索过，该问题未被报告过
- [ ] I have read the Q&A and I am sure my issue is not related to them / 我已经阅读过常见问题解答，且确定我的问题与它们无关
- [ ] I am using the latest debug CI version of Fuck Location and enabled verbose log / 我正在使用最新的 CI 调试版本，并且启用了详细日志

**Comment by q178666380** [comment]
xposed api只能在xposed 调用app的时候才能使用,android消息进程中调用就会报classnotfound异常,android9可以这么写,但是android11就不行了

**Comment by iusearch** [comment]
你有修过的版本吗，作者好像不维护了

**Comment by q178666380** [comment]
> 你有修过的版本吗，作者好像不维护了

lsp关闭xposed api调用保护,有时候默认是关闭的还是会报错,先开起来再关闭一下

**Comment by Y-stranger** [comment]
> 你有修过的版本吗，作者好像不维护了



> > 你有修过的版本吗，作者好像不维护了
> 
> lsp关闭xposed api调用保护,有时候默认是关闭的还是会报错,先开起来再关闭一下

作者好像于疫情时去世了唉

**Comment by byxiaorun** [comment]
人家作者活的好好的，他不想更新而已，别乱说，一个月前上线过
