### ISSUE TITLE
Report Issue / 反馈问题

### ISSUE THREAD

**Issue by einsbiao** [Mikotwa/FuckLocation#57]
### Steps to reproduce / 复现步骤

点击模块内设置

### Expected behaviour / 预期行为

正常运行

### Actual behaviour / 实际行为

崩溃退出

### Android version / Android 版本

13

### OEM Information / OEM 信息

miui14.0.8

### Logs / 日志

2023-04-04 14:40:26.859 11260-11260/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fuck.location, PID: 11260
    java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedBridge;
        at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282)
        at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73)
        at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56)
        at android.view.View.performClick(View.java:7544)
        at android.view.View.performClickInternal(View.java:7521)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29555)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8252)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
     Caused by: java.lang.ClassNotFoundException: de.robv.android.xposed.XposedBridge
        at fuck.location.xposed.helpers.ConfigGateway.readFakeLocation(ConfigGateway.kt:282) 
        at fuck.location.app.ui.activities.MainActivity.setFakeLocation(MainActivity.kt:73) 
        at fuck.location.app.ui.activities.MainActivity.onClick(MainActivity.kt:56) 
        at android.view.View.performClick(View.java:7544) 
        at android.view.View.performClickInternal(View.java:7521) 
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
        at android.view.View$PerformClick.run(View.java:29555) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8252) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) 

### Final checklist / 发布前检查清单

- [X] I have searched the Issues and Discussions to make sure it had not reported / 我已经在 Issue 和 Discussion 区搜索过，该问题未被报告过
- [X] I have read the Q&A and I am sure my issue is not related to them / 我已经阅读过常见问题解答，且确定我的问题与它们无关
- [ ] I am using the latest debug CI version of Fuck Location and enabled verbose log / 我正在使用最新的 CI 调试版本，并且启用了详细日志

**Comment by Weltolk** [comment]
same issue
